[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask-socketio = "*"
protobuf = "*"
pycryptodome = "*"
requests = "*"
tqdm = "*"
urllib3 = "<1.26.0"  # Newer versions seem to cause BadAuthentication errors.

[dev-packages]
pytest-cov = "*"
